"""
PR Agent — opens a GitHub PR with generated MCP artifacts.

Uses PyGithub (synchronous) wrapped in asyncio.run_in_executor
so it plays nicely with the async FastAPI event loop.
"""
import asyncio
from dataclasses import dataclass

from github import Github, GithubException


@dataclass
class PRResult:
    url: str
    number: int


class PRAgent:
    def __init__(self, token: str) -> None:
        self.gh = Github(token)

    async def open_pr(
        self,
        repo_name: str,
        files: dict[str, str],
        before_score: int,
        projected_score: int,
    ) -> PRResult:
        """Async wrapper — runs the synchronous PR logic in a thread pool."""
        loop = asyncio.get_running_loop()
        return await loop.run_in_executor(
            None,
            self._open_pr_sync,
            repo_name,
            files,
            before_score,
            projected_score,
        )

    def _open_pr_sync(
        self,
        repo_name: str,
        files: dict[str, str],
        before_score: int,
        projected_score: int,
    ) -> PRResult:
        repo = self.gh.get_repo(repo_name)
        branch = "agentready/mcp-integration"
        default_branch = repo.default_branch

        # Get the SHA of the default branch tip
        ref = repo.get_git_ref(f"heads/{default_branch}")

        # Create the feature branch (ignore if it already exists)
        try:
            repo.create_git_ref(f"refs/heads/{branch}", ref.object.sha)
        except GithubException:
            pass  # branch already exists — upsert files onto it

        # Upsert each generated file
        for path, content in files.items():
            try:
                existing = repo.get_contents(path, ref=branch)
                repo.update_file(
                    path,
                    f"chore(agentready): update {path}",
                    content,
                    existing.sha,  # type: ignore[arg-type]
                    branch=branch,
                )
            except GithubException:
                # File doesn't exist yet — create it
                repo.create_file(
                    path,
                    f"feat(agentready): add {path}",
                    content,
                    branch=branch,
                )

        pr_body = (
            "## Agent-Readiness Fix\n\n"
            f"| | Score |\n"
            f"|---|---|\n"
            f"| **Before** | {before_score}/100 |\n"
            f"| **Projected after merge** | {projected_score}/100 |\n\n"
            "### What's included\n"
            "- MCP server (`mcp-server/`) with typed tool schemas\n"
            "- `llms.txt` discoverability file\n"
            "- `docs/agent-guide.md` — agent integration guide\n"
            "- `evals/basic.ts` — basic eval harness\n\n"
            "_Generated by [AgentReady](https://agentready.dev)._"
        )

        pr = repo.create_pull(
            title=(
                f"[AgentReady] MCP server + agent layer "
                f"(score: {before_score} → {projected_score}/100)"
            ),
            body=pr_body,
            head=branch,
            base=default_branch,
        )
        return PRResult(url=pr.html_url, number=pr.number)
