"""
github_fix (Wirable) — open a real "agent-ready" PR on the user's repo.

When a user connects their GitHub repo (OAuth) and triggers the FIX, this module
uses their OAuth token to commit three generated files to a new branch and open a
pull request, via the GitHub REST API over httpx (no PyGithub, no shelling out):

  - llms.txt              llmstxt.org-style: product + the hosted MCP endpoint +
                          tools + how an agent authenticates.
  - AGENTS.md             instructions for coding agents working IN this repo:
                          use the MCP server, keep new endpoints agent-usable,
                          plus the concrete improvement checklist from the audit.
  - docs/agent-readiness.md  the audit findings (score + per-dimension verdict +
                          wrapped-card insights) + the RANKED suggested
                          improvements to make the product natively agent-ready.

The CONTENT of these files is generated by Claude (core.llm.anthropic_client)
from the audit dimensions + cards + target_url, degrading to a sensible template
when no Claude keys are configured.

Defensive contract: open_fix_pr NEVER raises — on any failure it returns
{"error": "..."}. On success it returns {"pr_url", "branch", "files": [...]}.
"""
from __future__ import annotations

import base64
import json
from typing import Any, Optional

import httpx
from loguru import logger

from ..core.llm import key_pool
from ..core.llm.anthropic_client import claude_text
from . import proxy_generator

_GH_API = "https://api.github.com"
_GH_VERSION = "2022-11-28"
_BRANCH = "wirable/agent-ready"
_TIMEOUT = 30.0

# Canonical dimension order + human labels (matches core.contracts).
_DIM_LABELS: dict[str, str] = {
    "api_surface": "Programmatic API surface",
    "auth": "Agent-deterministic auth",
    "error_quality": "Machine-readable errors",
    "idempotency": "Safe retries / idempotency",
    "mcp_availability": "MCP availability",
    "docs": "Agent-facing docs",
}
_DIM_ORDER = list(_DIM_LABELS.keys())


# ===========================================================================
# Public entry point
# ===========================================================================


async def open_fix_pr(
    repo_full_name: str,
    github_token: str,
    target_url: str,
    audit_dims: Any,
    cards: Optional[list] = None,
    proxy_mcp_url: str = "",
) -> dict:
    """Open the agent-ready PR on `repo_full_name` using `github_token`.

    repo_full_name : "owner/repo"
    github_token   : the user's OAuth token (Authorization: Bearer <token>)
    target_url     : the audited product URL (for file content)
    audit_dims     : list[{dim,passed,evidence}] OR map {dim:{passed,evidence}}
    cards          : the wrapped-card findings (optional)
    proxy_mcp_url   : the absolute URL of the hosted Wirable MCP proxy

    Returns {"pr_url", "branch", "files": [...]} on success,
            {"error": "..."} on any failure. Never raises.
    """
    if not repo_full_name or "/" not in repo_full_name:
        return {"error": "invalid repo_full_name (expected 'owner/repo')"}
    if not github_token:
        return {"error": "no github token"}

    dims = proxy_generator._dims_as_list(audit_dims)

    try:
        files = await _generate_files(target_url, dims, cards or [], proxy_mcp_url)
    except Exception:
        logger.exception("[github_fix] file generation failed")
        files = _template_files(target_url, dims, cards or [], proxy_mcp_url)

    headers = {
        "Authorization": f"Bearer {github_token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": _GH_VERSION,
        "User-Agent": "wirable-fix/1.0",
    }

    try:
        async with httpx.AsyncClient(
            base_url=_GH_API, headers=headers, timeout=_TIMEOUT
        ) as client:
            # 1) default branch + its head sha
            repo_resp = await client.get(f"/repos/{repo_full_name}")
            if repo_resp.status_code >= 400:
                return {"error": _gh_err("get repo", repo_resp)}
            default_branch = repo_resp.json().get("default_branch") or "main"

            ref_resp = await client.get(
                f"/repos/{repo_full_name}/git/ref/heads/{default_branch}"
            )
            if ref_resp.status_code >= 400:
                return {"error": _gh_err("get default ref", ref_resp)}
            base_sha = (ref_resp.json().get("object") or {}).get("sha")
            if not base_sha:
                return {"error": "could not resolve base branch sha"}

            # 2) create the branch ref (idempotent: tolerate "already exists")
            create_ref = await client.post(
                f"/repos/{repo_full_name}/git/refs",
                json={"ref": f"refs/heads/{_BRANCH}", "sha": base_sha},
            )
            if create_ref.status_code >= 400 and not _ref_exists(create_ref):
                return {"error": _gh_err("create branch", create_ref)}

            # 3) create/update each file on the branch (Contents API)
            written: list[str] = []
            for path, content in files.items():
                ok, err = await _put_file(
                    client, repo_full_name, _BRANCH, path, content
                )
                if ok:
                    written.append(path)
                else:
                    logger.warning("[github_fix] put %s failed: %s", path, err)

            if not written:
                return {"error": "no files could be written to the branch"}

            # 4) open the pull request (idempotent: reuse an existing open PR)
            pr_url = await _open_or_get_pr(
                client, repo_full_name, _BRANCH, default_branch, target_url
            )
            if not pr_url:
                return {"error": "files committed but PR could not be opened"}

            return {"pr_url": pr_url, "branch": _BRANCH, "files": written}
    except Exception as exc:
        logger.exception("[github_fix] open_fix_pr failed")
        return {"error": str(exc)}


# ===========================================================================
# GitHub REST helpers
# ===========================================================================


def _gh_err(stage: str, resp: "httpx.Response") -> str:
    try:
        msg = resp.json().get("message", "")
    except Exception:
        msg = resp.text[:200]
    return f"github {stage}: {resp.status_code} {msg}"


def _ref_exists(resp: "httpx.Response") -> bool:
    """422 'Reference already exists' is fine — the branch is reusable."""
    if resp.status_code != 422:
        return False
    try:
        return "already exists" in (resp.json().get("message", "") or "").lower()
    except Exception:
        return False


async def _put_file(
    client: "httpx.AsyncClient",
    repo: str,
    branch: str,
    path: str,
    content: str,
) -> tuple[bool, str]:
    """Create or update a file on `branch` via the Contents API. Idempotent."""
    # Need the existing blob sha to update a file that already exists on branch.
    sha: Optional[str] = None
    try:
        get_resp = await client.get(
            f"/repos/{repo}/contents/{path}", params={"ref": branch}
        )
        if get_resp.status_code == 200:
            body = get_resp.json()
            if isinstance(body, dict):
                sha = body.get("sha")
    except Exception:
        sha = None

    payload: dict[str, Any] = {
        "message": f"chore(wirable): add {path} (agent-ready)",
        "content": base64.b64encode(content.encode("utf-8")).decode("ascii"),
        "branch": branch,
    }
    if sha:
        payload["sha"] = sha

    try:
        put_resp = await client.put(
            f"/repos/{repo}/contents/{path}", json=payload
        )
        if put_resp.status_code >= 400:
            return False, _gh_err(f"put {path}", put_resp)
        return True, ""
    except Exception as exc:
        return False, str(exc)


async def _open_or_get_pr(
    client: "httpx.AsyncClient",
    repo: str,
    head: str,
    base: str,
    target_url: str,
) -> str:
    """Open a PR; if one already exists for the branch, return its url."""
    title = "Make this product agent-ready (Wirable)"
    body = (
        "This PR was generated by [Wirable](https://wirable) to make this "
        f"product usable by autonomous AI agents.\n\n"
        "It adds three files:\n"
        "- `llms.txt`: an llmstxt.org-style index pointing agents at the hosted "
        "MCP endpoint and tools.\n"
        "- `AGENTS.md`: instructions for coding agents working in this repo, "
        "plus the audit's improvement checklist.\n"
        "- `docs/agent-readiness.md`: the full audit findings and a ranked plan "
        "to make the product *natively* agent-ready.\n\n"
        f"Audited target: {target_url}\n"
    )
    try:
        create = await client.post(
            f"/repos/{repo}/pulls",
            json={"title": title, "head": head, "base": base, "body": body},
        )
        if create.status_code < 400:
            return create.json().get("html_url", "")
        # Already exists -> look it up.
        owner = repo.split("/")[0]
        existing = await client.get(
            f"/repos/{repo}/pulls",
            params={"head": f"{owner}:{head}", "state": "open"},
        )
        if existing.status_code < 400:
            arr = existing.json()
            if isinstance(arr, list) and arr:
                return arr[0].get("html_url", "")
        logger.warning("[github_fix] open PR failed: %s", _gh_err("pulls", create))
        return ""
    except Exception:
        logger.exception("[github_fix] open_or_get_pr failed")
        return ""


# ===========================================================================
# File content generation (Claude with template fallback)
# ===========================================================================


async def _generate_files(
    target_url: str, dims: list[dict], cards: list, proxy_mcp_url: str
) -> dict[str, str]:
    """Return {path: content} for the three files. Claude-written when keyed."""
    suggestions = await proxy_generator.suggested_improvements(dims, cards)
    if not key_pool.has_keys():
        files = _template_files(target_url, dims, cards, proxy_mcp_url)
        # still inject the (template) suggestions into the docs
        return files

    llms = await _gen_llms_txt(target_url, dims, proxy_mcp_url)
    agents = await _gen_agents_md(target_url, suggestions, proxy_mcp_url)
    docs = _gen_docs_md(target_url, dims, cards, suggestions)
    return {
        "llms.txt": llms or _template_llms(target_url, proxy_mcp_url),
        ".well-known/mcp.json": _well_known_mcp(target_url, proxy_mcp_url),
        "AGENTS.md": agents or _template_agents(target_url, suggestions, proxy_mcp_url),
        "docs/agent-readiness.md": docs,
    }


async def _gen_llms_txt(target_url: str, dims: list[dict], proxy_mcp_url: str) -> str:
    system = (
        "You write llms.txt files (llmstxt.org format): an H1 product name, a "
        "one-line blockquote summary, then H2 sections. Be concise and factual. "
        "Write plainly. Do not use em-dashes. Avoid marketing buzzwords and AI-cliche phrasing. "
        "Output ONLY the file content (markdown), no fences, no commentary."
    )
    prompt = (
        f"Product URL: {target_url}\n"
        f"Hosted MCP endpoint (agents call this): {proxy_mcp_url}\n\n"
        "Write an llms.txt that: names the product; gives a one-line summary; "
        "has an '## MCP' section stating the MCP endpoint URL and transport "
        "(http) and that an agent authenticates with an Authorization: Bearer "
        "<agent-key> header; has a '## How agents should use this' section. "
        "Keep it under 40 lines."
    )
    return (await claude_text(prompt, system=system, max_tokens=700)).strip()


async def _gen_agents_md(
    target_url: str, suggestions: list[str], proxy_mcp_url: str
) -> str:
    system = (
        "You write AGENTS.md files that coding agents load when working in a "
        "repository. Be directive and concise. Write plainly. Do not use em-dashes. "
        "Avoid marketing buzzwords and AI-cliche phrasing. Output ONLY markdown, no fences."
    )
    checklist = "\n".join(f"- [ ] {s}" for s in suggestions) or "- [ ] (none)"
    prompt = (
        f"Product: {target_url}\n"
        f"Hosted MCP server agents should use: {proxy_mcp_url}\n\n"
        "Write an AGENTS.md that tells coding agents: this product is now "
        "agent-ready via Wirable; use the MCP server at that URL; when adding "
        "endpoints keep them agent-usable (return structured machine-readable "
        "errors with stable codes, support Idempotency-Key on mutations, and "
        "expose new endpoints in llms.txt). Then include this exact improvement "
        f"checklist verbatim under a '## Make it natively agent-ready' heading:\n"
        f"{checklist}"
    )
    return (await claude_text(prompt, system=system, max_tokens=900)).strip()


def _gen_docs_md(
    target_url: str, dims: list[dict], cards: list, suggestions: list[str]
) -> str:
    """The audit-findings doc is deterministic (it's a report, not prose)."""
    return _template_docs(target_url, dims, cards, suggestions)


# ===========================================================================
# Templates (deterministic fallback — used when no Claude keys)
# ===========================================================================


def _well_known_mcp(target_url: str, proxy_mcp_url: str) -> str:
    """The canonical .well-known/mcp.json discovery manifest pointing agents at the
    hosted Wirable MCP. This is the standard place agents look for an MCP server."""
    name = _product_name(target_url)
    return json.dumps(
        {
            "schema_version": "2024-11-05",
            "name": name,
            "description": f"Agent-ready MCP endpoint for {name}, hosted by Wirable.",
            "mcp": {"url": proxy_mcp_url, "transport": "http"},
            "endpoint": proxy_mcp_url,
        },
        indent=2,
    )


def _template_files(
    target_url: str, dims: list[dict], cards: list, proxy_mcp_url: str
) -> dict[str, str]:
    suggestions = [s for s in _template_suggestions(dims)]
    return {
        "llms.txt": _template_llms(target_url, proxy_mcp_url),
        ".well-known/mcp.json": _well_known_mcp(target_url, proxy_mcp_url),
        "AGENTS.md": _template_agents(target_url, suggestions, proxy_mcp_url),
        "docs/agent-readiness.md": _template_docs(
            target_url, dims, cards, suggestions
        ),
    }


def _template_suggestions(dims: list[dict]) -> list[str]:
    failed = {d.get("dim") for d in dims if not d.get("passed")}
    out: list[str] = []
    for key in _DIM_ORDER:
        if key in failed:
            out.append(proxy_generator._DIM_FIX_TEMPLATES.get(key, ""))
    return [s for s in out if s]


def _template_llms(target_url: str, proxy_mcp_url: str) -> str:
    name = _product_name(target_url)
    return (
        f"# {name}\n\n"
        f"> {name} is now agent-ready via Wirable: a hosted MCP server exposes "
        "typed tools, normalized errors, and idempotent retries.\n\n"
        f"## Product\n- Website: {target_url}\n\n"
        "## MCP\n"
        f"- Endpoint: {proxy_mcp_url} (transport: http)\n"
        "- Authentication: send `Authorization: Bearer <agent-key>` with each "
        "`tools/call`. Discover tools with the `tools/list` method.\n\n"
        "## How agents should use this\n"
        "- List tools, then call them over MCP-over-HTTP (JSON-RPC).\n"
        "- Errors are normalized to `{success, error_code, retryable}`. Retry "
        "only when `retryable` is true.\n"
    )


def _template_agents(
    target_url: str, suggestions: list[str], proxy_mcp_url: str
) -> str:
    checklist = "\n".join(f"- [ ] {s}" for s in suggestions) or "- [ ] (no gaps found)"
    return (
        "# AGENTS.md\n\n"
        "This product is now **agent-ready** via "
        "[Wirable](https://wirable).\n\n"
        "## Use the MCP server\n"
        f"Agents should use the MCP server at `{proxy_mcp_url}` "
        "(transport: http). Authenticate with `Authorization: Bearer "
        "<agent-key>`. Use `tools/list` to discover tools and `tools/call` to "
        "invoke them.\n\n"
        "## When adding endpoints, keep them agent-usable\n"
        "- Return **structured, machine-readable errors**: a stable string "
        "`error_code`, a boolean `retryable`, and an actionable message. Never "
        "wrap a failure in a 200.\n"
        "- Support **idempotency keys** (`Idempotency-Key` header) on mutating "
        "endpoints so retries don't duplicate side effects.\n"
        "- **Expose new endpoints in `llms.txt`** so agents can discover them.\n\n"
        "## Make it natively agent-ready\n"
        "The audit of "
        f"{target_url} surfaced these improvements (highest impact first):\n\n"
        f"{checklist}\n"
    )


def _template_docs(
    target_url: str, dims: list[dict], cards: list, suggestions: list[str]
) -> str:
    # Score = sum of weights of passed dimensions (mirrors the rubric weights).
    weights = {
        "api_surface": 20, "auth": 20, "error_quality": 15,
        "idempotency": 15, "mcp_availability": 20, "docs": 10,
    }
    score = sum(weights.get(d.get("dim", ""), 0) for d in dims if d.get("passed"))

    lines: list[str] = []
    lines.append("# Agent-readiness report\n")
    lines.append(
        f"Audited target: **{target_url}**  \n"
        f"Generated by [Wirable](https://wirable).\n"
    )
    lines.append(f"\n## Score: {score}/100\n")

    lines.append("\n## Dimensions\n")
    lines.append("| Dimension | Verdict | Evidence |")
    lines.append("| --- | --- | --- |")
    by_dim = {d.get("dim"): d for d in dims}
    for key in _DIM_ORDER:
        d = by_dim.get(key, {})
        verdict = "✅ pass" if d.get("passed") else "❌ fail"
        evidence = str(d.get("evidence", "") or "—").replace("|", "\\|")[:300]
        lines.append(f"| {_DIM_LABELS[key]} | {verdict} | {evidence} |")

    if cards:
        lines.append("\n## Findings\n")
        for c in cards:
            if not isinstance(c, dict):
                continue
            headline = str(c.get("headline", "") or "").strip()
            detail = str(c.get("detail", "") or "").strip()
            if headline or detail:
                lines.append(f"- **{headline}**: {detail}")

    lines.append("\n## Suggested improvements (make it natively agent-ready)\n")
    if suggestions:
        for i, s in enumerate(suggestions, 1):
            lines.append(f"{i}. {s}")
    else:
        lines.append("No gaps found. The product is already agent-ready.")

    lines.append(
        "\n---\n"
        "Until these land, the hosted Wirable MCP proxy bridges the gap so "
        "agents can use this product today.\n"
    )
    return "\n".join(lines) + "\n"


def _product_name(target_url: str) -> str:
    host = (target_url or "").split("//")[-1].split("/")[0]
    host = host.removeprefix("www.")
    label = host.split(".")[0] if host else "This product"
    return label.capitalize() if label else "This product"
